# Toml Bombadil configuration
dotfiles_dir = ".dotfiles"

[settings]
posthooks = ["zsh -c doctor"]

[settings.dots]
# Neovim, the editor
neovim = { source = "nvim", target = ".config/nvim" }

# Kitty, the terminal emulator
kitty = { source = "kitty", target = ".config/kitty" }

# Git - for git stuff, you know?
git = { source = "git/config", target = ".gitconfig" }

# Shell things, like aliases
shell_aliases = { source = "shell/aliases", target = ".config/aliases" }
shell_config = { source = "shell/zshrc", target = ".zshrc" }
the_doctor = { source = "shell/doctor.sh", target = ".local/bin/doctor"}

# Language things
R_linting = { source = "languages/R/lintr", target = ".lintr" }

